package com.pojo;

// Generated Oct 4, 2018 1:52:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * Addfertilizer generated by hbm2java
 */
public class Addfertilizer implements java.io.Serializable {

	private Integer fid;
	private String fertilizername;
	private String fertilizerdetails;
	private String fertilizerquantity;
	private String fertilizerimage;

	public Addfertilizer() {
	}

	public Addfertilizer(String fertilizername, String fertilizerdetails, String fertilizerquantity,
			String fertilizerimage) {
		this.fertilizername = fertilizername;
		this.fertilizerdetails = fertilizerdetails;
		this.fertilizerquantity = fertilizerquantity;
		this.fertilizerimage = fertilizerimage;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public String getFertilizername() {
		return this.fertilizername;
	}

	public void setFertilizername(String fertilizername) {
		this.fertilizername = fertilizername;
	}

	public String getFertilizerdetails() {
		return this.fertilizerdetails;
	}

	public void setFertilizerdetails(String fertilizerdetails) {
		this.fertilizerdetails = fertilizerdetails;
	}

	public String getFertilizerquantity() {
		return this.fertilizerquantity;
	}

	public void setFertilizerquantity(String fertilizerquantity) {
		this.fertilizerquantity = fertilizerquantity;
	}

	public String getFertilizerimage() {
		return this.fertilizerimage;
	}

	public void setFertilizerimage(String fertilizerimage) {
		this.fertilizerimage = fertilizerimage;
	}

}
