package com.pojo;

// Generated Oct 4, 2018 1:52:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * Addmachinery generated by hbm2java
 */
public class Addmachinery implements java.io.Serializable {

	private Integer mid;
	private String machinename;
	private String description;
	private String machineimage;

	public Addmachinery() {
	}

	public Addmachinery(String machinename, String description, String machineimage) {
		this.machinename = machinename;
		this.description = description;
		this.machineimage = machineimage;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getMachinename() {
		return this.machinename;
	}

	public void setMachinename(String machinename) {
		this.machinename = machinename;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMachineimage() {
		return this.machineimage;
	}

	public void setMachineimage(String machineimage) {
		this.machineimage = machineimage;
	}

}
