package com.pojo;

// Generated Oct 4, 2018 1:52:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sellcrops generated by hbm2java
 */
public class Sellcrops implements java.io.Serializable {

	private Integer cid;
	private String cropname;
	private String quaintity;
	private String cropimage;
	private Integer contact;
	private String address;

	public Sellcrops() {
	}

	public Sellcrops(String cropname, String quaintity, String cropimage, Integer contact, String address) {
		this.cropname = cropname;
		this.quaintity = quaintity;
		this.cropimage = cropimage;
		this.contact = contact;
		this.address = address;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCropname() {
		return this.cropname;
	}

	public void setCropname(String cropname) {
		this.cropname = cropname;
	}

	public String getQuaintity() {
		return this.quaintity;
	}

	public void setQuaintity(String quaintity) {
		this.quaintity = quaintity;
	}

	public String getCropimage() {
		return this.cropimage;
	}

	public void setCropimage(String cropimage) {
		this.cropimage = cropimage;
	}

	public Integer getContact() {
		return this.contact;
	}

	public void setContact(Integer contact) {
		this.contact = contact;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
